version: '3.8'
services:
  backend:
    volumes:
      - "./:/app"
    build: .
    depends_on:
      - super__redis
      - super__postgres
    networks:
      - super_network
    env_file:
      - .env
    command: ["/app/wait-for-it.sh", "super__postgres:5432","-t","60","--","/app/entrypoint.sh"]

  celery:
    volumes:
      - "./:/app"
      - "${EXTERNAL_RESOURCE_DIR:-./workspace}:/app/ext"
    build: .
    depends_on:
      - super__redis
      - super__postgres
    networks:
      - super_network
    env_file:
      - .env
    command: ["/app/entrypoint_celery.sh"]

  gui:
    build:
      context: ./gui
      args:
        NEXT_PUBLIC_API_BASE_URL: "/api"
    networks:
      - super_network

  super__redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - super_network
    volumes:
      - redis_data:/data

  super__postgres:
    image: "docker.io/library/postgres:15"
    environment:
      - POSTGRES_USER=superagi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=super_agi_main
    volumes:
      - superagi_postgres_data:/var/lib/postgresql/data/
    networks:
      - super_network

  proxy:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    networks:
      - super_network
    depends_on:
      - backend
      - gui
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  super_network:
    driver: bridge

volumes:
  superagi_postgres_data:
  redis_data: